tasks:
  - init: echo "Replace me with a build script for the project."
    command: apt-get install libsndfile1-dev && cd userPortal/voice_backend && pip3 install -r requirements.txt && pip3 install django djangorestframework
