# Generated by Django 3.0.5 on 2020-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateAudioRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioName', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='audiouploadmodel',
            name='username_ofaudiouploaded',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
